name: Add PDF to Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run your script to generate the PDF file
      - name: Generate PDF
        run: ./generate_pdf.sh  # Replace with the command to generate the PDF file

      # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release automatically created for tag ${{ github.ref }}

      # Upload the generated PDF as a release asset
      - name: Upload PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/generated_pdf.pdf  # Path to your generated PDF file
          asset_name: my_generated_pdf.pdf  # Name for the PDF file in the release
          asset_content_type: application/pdf
