name: Generate PDF

on:
  push:
    branches:
      - main

jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate PDF
        run: |
          python generate_pdf.py

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: generated_pdf.pdf
