name: Create Release on Tag 

on:
  push:
    tag:
      - '*'

jobs:
  create_release:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          release_name: Release ${{ steps.extract_tag.outputs.tag_name }}
          draft: false
          prerelease: false
          body: |
            Release automatically created from tag ${{ steps.extract_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
